# Generated by Django 3.0.3 on 2023-12-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='title_tag',
            field=models.CharField(default='welcome to my site', max_length=250),
        ),
    ]
