# Generated by Django 3.0.3 on 2023-12-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
